### ISSUE TITLE
AMASSS do not work 

### ISSUE THREAD

**Issue by YOU-DDS** [DCBIA-OrthoLab/SlicerAutomatedDentalTools#42]
Good evening,

I am YOU, I am working in a project segmented the The whole bone of the scalp I am trying to follow the Tutorial video by DCBIA. 

But it did not work. I also find it hard to insert data in Model's Folder which I cannot do the same is video Tutorial 
https://www.youtube.com/watch?v=d6penNStUQE
https://www.youtube.com/watch?v=Sg6oaOclOV8&t=174s

Please could anyone tell me how to solve this problem?

Best regard,
YOU

**Comment by AlyxR** [comment]
Greetings, I have an issue with getting any results, AMASSS seems to be processing the first frame and complete it with no result. 
(I am using .dcm files, which are seen correctly)

**Comment by luciacev** [comment]
AMASSS now does support .dcm files. However, because .dcm files are a stack of files and also contain metadata, AMASSS is more efficient for .nrrd, .nii, or.gipl.gz files. We would recommend that you first anonymize your datasets to remove HIPAA identifiers using Slicer Batch Anonymize extension to remove the images metadata and save it in on the file formats to run it more efficiently using AMASSS.
